In [2]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
%cd /content/drive/MyDrive/NLP_Project/testMarlin/MARLIN/test/videos

/content/drive/MyDrive/NLP_Project/testMarlin/MARLIN/test/videos


In [ ]:
!pip3 install faster-whisper ffmpeg-python

In [ ]:
!pip3 freeze > /content/requirements.txt

In [ ]:
import time
import math
import ffmpeg

from faster_whisper import WhisperModel

model = WhisperModel("large")



In [ ]:
input_video = "video02.mp4"
input_video_name = input_video.replace(".mp4", "")

In [ ]:
def extract_audio(input_video, input_video_name):
    extracted_audio = f"audio-{input_video_name}.wav"
    stream = ffmpeg.input(input_video)
    stream = ffmpeg.output(stream, extracted_audio)
    ffmpeg.run(stream, overwrite_output=True)
    return extracted_audio

In [ ]:
extracted_audio = extract_audio(input_video, input_video_name)

In [ ]:
def transcribe(audio):
    segments, info = model.transcribe(audio)
    language = info[0]
    print("Transcription language", info[0])
    segments = list(segments)
    for segment in segments:
        # print(segment)
        print("[%.2fs -> %.2fs] %s" %
              (segment.start, segment.end, segment.text))
    return language, segments

In [ ]:
language, segments = transcribe(audio=extracted_audio)

Transcription language en
[0.00s -> 2.00s]  Hey, this is Ken from AES.
[2.00s -> 6.00s]  Sometimes we're asked about the difference between what we do and a textbook.
[6.00s -> 8.00s]  Let's talk about textbooks first.
[8.00s -> 13.00s]  The best thing about a textbook is you can buy it once and you can keep using it for three or four years.


In [ ]:
segments

[Segment(id=1, seek=1300, start=0.0, end=2.0, text=' Hey, this is Ken from AES.', tokens=[50365, 1911, 11, 341, 307, 8273, 490, 316, 2358, 13, 50465], temperature=0.0, avg_logprob=-0.13012695545330644, compression_ratio=1.4698795180722892, no_speech_prob=0.0182342529296875, words=None),
 Segment(id=2, seek=1300, start=2.0, end=6.0, text=" Sometimes we're asked about the difference between what we do and a textbook.", tokens=[50465, 4803, 321, 434, 2351, 466, 264, 2649, 1296, 437, 321, 360, 293, 257, 25591, 13, 50665], temperature=0.0, avg_logprob=-0.13012695545330644, compression_ratio=1.4698795180722892, no_speech_prob=0.0182342529296875, words=None),
 Segment(id=3, seek=1300, start=6.0, end=8.0, text=" Let's talk about textbooks first.", tokens=[50665, 961, 311, 751, 466, 33587, 700, 13, 50765], temperature=0.0, avg_logprob=-0.13012695545330644, compression_ratio=1.4698795180722892, no_speech_prob=0.0182342529296875, words=None),
 Segment(id=4, seek=1300, start=8.0, end=13.0, text=' 

In [ ]:
def format_time(seconds):

    hours = math.floor(seconds / 3600)
    seconds %= 3600
    minutes = math.floor(seconds / 60)
    seconds %= 60
    milliseconds = round((seconds - math.floor(seconds)) * 1000)
    seconds = math.floor(seconds)
    formatted_time = f"{hours:02d}:{minutes:02d}:{seconds:01d},{milliseconds:03d}"

    return formatted_time

In [ ]:
def generate_subtitle_file(language, segments):

    subtitle_file = f"sub-{input_video_name}.{language}.srt"
    text = ""
    for index, segment in enumerate(segments):
        segment_start = format_time(segment.start)
        segment_end = format_time(segment.end)
        text += f"{str(index+1)} \n"
        text += f"{segment_start} --> {segment_end} \n"
        text += f"{segment.text} \n"
        text += "\n"

    f = open(subtitle_file, "w")
    f.write(text)
    f.close()

    return subtitle_file

In [ ]:

subtitle_file = generate_subtitle_file(
language=language,
segments=segments
)

In [ ]:
def add_subtitle_to_video(soft_subtitle, subtitle_file,  subtitle_language, input_video, input_video_name):

    video_input_stream = ffmpeg.input(input_video)
    subtitle_input_stream = ffmpeg.input(subtitle_file)
    output_video = f"output-{input_video_name}.mp4"
    subtitle_track_title = subtitle_file.replace(".srt", "")

    if soft_subtitle:
        stream = ffmpeg.output(
            video_input_stream, subtitle_input_stream, output_video, **{"c": "copy", "c:s": "mov_text"},
            **{"metadata:s:s:0": f"language={subtitle_language}",
            "metadata:s:s:0": f"title={subtitle_track_title}"}
        )
        ffmpeg.run(stream, overwrite_output=True)
    else:
        stream = ffmpeg.output(video_input_stream, output_video,
                                vf=f"subtitles={subtitle_file}")
        ffmpeg.run(stream, overwrite_output=True)

In [ ]:
add_subtitle_to_video(
        soft_subtitle=False,
        subtitle_file=subtitle_file,
        subtitle_language=language,
        input_video=input_video,
        input_video_name=input_video_name
    )

In [ ]:
# Install required libraries
!pip install googletrans==3.1.0a0


In [ ]:
segments, info = model.transcribe(extracted_audio)


In [ ]:
segments = list(segments)

In [ ]:
text = []
for segment in segments:
  text.append(segment.text)


In [ ]:
text

[' Hey, this is Ken from AES.',
 " Sometimes we're asked about the difference between what we do and a textbook.",
 " Let's talk about textbooks first.",
 ' The best thing about a textbook is you can buy it once and you can keep using it for three or four years.']

In [ ]:
%cd /content/drive/MyDrive/NLP_Project

/content/drive/MyDrive/NLP_Project


In [ ]:
# Open the file for writing
with open("sentences_video03.txt", "w") as text_file:
  # Loop through each element in the array
  for line in text:
    print(line)
    # Write the line to the file with a newline character at the end
    text_file.write(line + "\n")

 Hey, this is Ken from AES.
 Sometimes we're asked about the difference between what we do and a textbook.
 Let's talk about textbooks first.
 The best thing about a textbook is you can buy it once and you can keep using it for three or four years.


In [ ]:
from googletrans import Translator




# Initialize translator
translator = Translator()
# Define translation language (replace 'fr' with your desired language code)
target_language = 'tr'

# Translate the text
translated = translator.translate(text, dest=target_language)
translated[0].text


"Merhaba, bu AES'ten Ken."

In [ ]:
translated_text = [element.text for element  in translated]
translated_text

["Merhaba, bu AES'ten Ken.",
 'Bazen bize yaptıklarımız ile bir ders kitabı arasındaki fark sorulur.',
 'Önce ders kitaplarından bahsedelim.',
 'Bir ders kitabının en iyi yanı, onu bir kere satın alıp üç ya da dört yıl boyunca kullanmaya devam edebilmenizdir.']

In [ ]:



# Print the translated text
print(f"Original Text: {text}")
print(f"Translated Text ({target_language}): {translated_text}")

Original Text: [' Hey, this is Ken from AES.', " Sometimes we're asked about the difference between what we do and a textbook.", " Let's talk about textbooks first.", ' The best thing about a textbook is you can buy it once and you can keep using it for three or four years.']
Translated Text (tr): ["Merhaba, bu AES'ten Ken.", 'Bazen bize yaptıklarımız ile bir ders kitabı arasındaki fark sorulur.', 'Önce ders kitaplarından bahsedelim.', 'Bir ders kitabının en iyi yanı, onu bir kere satın alıp üç ya da dört yıl boyunca kullanmaya devam edebilmenizdir.']


In [ ]:
%cd /content/drive/MyDrive/NLP_Project/testMarlin/MARLIN/test/videos

/content/drive/MyDrive/NLP_Project/testMarlin/MARLIN/test/videos


In [ ]:
import ffmpeg
from googletrans import Translator

def add_subtitle_to_video(soft_subtitle, subtitle_file, subtitle_language, input_video, input_video_name):
    video_input_stream = ffmpeg.input(input_video)
    subtitle_input_stream = ffmpeg.input(subtitle_file)
    output_video = f"output-{input_video_name}.mp4"
    subtitle_track_title = subtitle_file.replace(".srt", "")

    if soft_subtitle:
        stream = ffmpeg.output(
            video_input_stream, subtitle_input_stream, output_video, **{"c": "copy", "c:s": "mov_text"},
            **{"metadata:s:s:0": f"language={subtitle_language}",
               "metadata:s:s:0": f"title={subtitle_track_title}"}
        )
        ffmpeg.run(stream, overwrite_output=True)
    else:
        stream = ffmpeg.output(video_input_stream, output_video,
                               vf=f"subtitles={subtitle_file}")
        ffmpeg.run(stream, overwrite_output=True)

In [ ]:


# Initialize translator
translator = Translator()
target_language = 'tr'

# Read the subtitle file
with open('/content/drive/MyDrive/NLP_Project/testMarlin/MARLIN/test/videos/sub-video02.en.srt', 'r', encoding='utf-8') as file:
    lines = file.readlines()


In [ ]:

translated_lines = []
text_block = ""
time_block = ""


In [ ]:

for line in lines:
    if '-->' in line:
        if text_block:
            translated = translator.translate(text_block.strip(), dest=target_language).text
            translated_lines.append(text_block.strip())
            translated_lines.append(translated + "\n")
        text_block = ""
        time_block = line.strip()
        translated_lines.append(time_block)
    elif line.strip().isdigit():
        translated_lines.append(line.strip())
    else:
        text_block += line


In [ ]:

if text_block:
    translated = translator.translate(text_block.strip(), dest=target_language).text
    translated_lines.append(text_block.strip())
    translated_lines.append(translated + "\n")

# Write translated subtitles to a new file
translated_subtitle_file = 'translated_subtitles.srt'
with open(translated_subtitle_file, 'w', encoding='utf-8') as file:
    for line in translated_lines:
        file.write(line + '\n')


In [ ]:

# Use the function to add subtitles to the video
input_video = 'video02.mp4'  # Replace with your input video file
input_video_name = 'video02'  # Replace with your video name without extension
subtitle_language = 'tr'  # Turkish language code
soft_subtitle = False  # Set to True for soft subtitles, False for hard subtitles

add_subtitle_to_video(soft_subtitle, translated_subtitle_file, subtitle_language, input_video, input_video_name)


In [3]:
import torch

def read_data(filename):
  """Reads data from a file into a PyTorch tensor."""
  with open(filename, 'r') as f:
    data_lines = f.readlines()  # Read all lines

  data = []
  for line in data_lines:
    data.append([float(x) for x in line.strip().split()])  # Split and convert each line

  return torch.tensor(data)  # Create a 2D tensor

def element_wise_dot_product(file1, file2):
  """Reads data from files, performs element-wise dot product, and applies softmax."""
  data1 = read_data(file1)
  data2 = read_data(file2)
  print(data1)
  print(data2)
  # Ensure data has the same dimensions
  if data1.size() != data2.size():
    raise ValueError("Data in files must have the same dimensions for element-wise multiplication.")

  # Calculate element-wise dot product
  element_wise_product = data1 * data2  # Use element-wise multiplication operator
  print(element_wise_product)
  # Apply softmax on each row (assuming data points are in rows)
  softmax = torch.nn.functional.softmax(element_wise_product, dim=1)

  return softmax

# Example usage (replace 'file1.txt' and 'file2.txt' with your actual file paths)
result = element_wise_dot_product('/content/drive/MyDrive/NLP_Project/softmax_output_of_text.txt', '/content/drive/MyDrive/NLP_Project/softmax_output_of_video.txt')
print(result)


tensor([[0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.3118],
        [0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.3118],
        [0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.3118],
        [0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.1147, 0.3118]])
tensor([[0.0303, 0.0161, 0.0646, 0.8046, 0.0200, 0.0340, 0.0303],
        [0.0996, 0.0224, 0.5680, 0.1312, 0.0486, 0.0900, 0.0401],
        [0.2436, 0.0234, 0.4406, 0.0983, 0.0555, 0.0959, 0.0426],
        [0.3570, 0.0242, 0.3074, 0.0857, 0.0656, 0.1321, 0.0281]])
tensor([[0.0035, 0.0018, 0.0074, 0.0923, 0.0023, 0.0039, 0.0095],
        [0.0114, 0.0026, 0.0652, 0.0150, 0.0056, 0.0103, 0.0125],
        [0.0279, 0.0027, 0.0505, 0.0113, 0.0064, 0.0110, 0.0133],
        [0.0409, 0.0028, 0.0353, 0.0098, 0.0075, 0.0151, 0.0088]])
tensor([[0.1408, 0.1406, 0.1414, 0.1539, 0.1407, 0.1409, 0.1417],
        [0.1420, 0.1407, 0.1498, 0.1425, 0.1411, 0.1418, 0.1421],
        [0.1443, 0.1407, 0.1476, 0.1419, 0.1412, 0.1419, 0.1422],
       

In [4]:
result_np = result.numpy()

In [5]:
%cd /content/drive/MyDrive/NLP_Project
# Save the softmax arrays to a text file
with open("softmax_result.txt", "w") as file:
    for array in result_np:
        file.write(' '.join([str(elem) for elem in array]) + '\n')

/content/drive/MyDrive/NLP_Project


In [6]:
import numpy as np
final_result = np.argmax(result, axis=1)
final_result

tensor([3, 2, 2, 0])

In [7]:
# Define a mapping dictionary
label_mapping = {'surprise':0, 'worry':1, 'hate':2, 'happiness':3, 'sadness':4, 'anger':5, 'neutral':6}

In [10]:
def get_key_from_value(dictionary, value):
    for key, val in dictionary.items():
        if val == value:
            return key
    return None  # If the value is not found

In [11]:
res = [get_key_from_value(label_mapping, label) for label in final_result]
res

['happiness', 'hate', 'hate', 'surprise']

In [17]:
%cd /content/drive/MyDrive/NLP_Project

/content/drive/MyDrive/NLP_Project


In [14]:
!pip install opencv-python-headless moviepy


In [19]:
import cv2
from moviepy.editor import VideoFileClip, AudioFileClip

# Define your list of texts
text_list = res
input_video = "/content/drive/MyDrive/NLP_Project/testMarlin/MARLIN/test/videos/output-video02.mp4"  # Get the uploaded video filename
output_video_with_audio = "output_video_with_audio.mp4"

# Open the video file with OpenCV
cap = cv2.VideoCapture(input_video)
fps = int(cap.get(cv2.CAP_PROP_FPS))
frame_count = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
duration = frame_count / fps

# Calculate the duration each text should be displayed
num_texts = len(text_list)
display_duration = duration / num_texts
frames_per_text = int(display_duration * fps)

# Get video properties
width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

# Define the codec and create a temporary VideoWriter object
fourcc = cv2.VideoWriter_fourcc(*'mp4v')
temp_output = "temp_output.mp4"
out = cv2.VideoWriter(temp_output, fourcc, fps, (width, height))

current_text_index = 0
frame_index = 0

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Calculate which text to display based on frame index
    current_text_index = frame_index // frames_per_text
    if current_text_index >= num_texts:
        current_text_index = num_texts - 1

    text = "Sentiment: " + text_list[current_text_index]

    # Put the text on the frame
    cv2.putText(frame, text, (10, 50), cv2.FONT_HERSHEY_SIMPLEX, 2, (255, 255, 255), 3, cv2.LINE_AA)

    # Write the frame to the output video
    out.write(frame)

    frame_index += 1

# Release everything if job is finished
cap.release()
out.release()
cv2.destroyAllWindows()

# Use moviepy to add the original audio back to the processed video
original_video = VideoFileClip(input_video)
processed_video = VideoFileClip(temp_output)

final_video = processed_video.set_audio(original_video.audio)
final_video.write_videofile(output_video_with_audio, codec="libx264")




Moviepy - Building video output_video_with_audio.mp4.
MoviePy - Writing audio in output_video_with_audioTEMP_MPY_wvf_snd.mp3


MoviePy - Done.
Moviepy - Writing video output_video_with_audio.mp4



Moviepy - Done !
Moviepy - video ready output_video_with_audio.mp4
